Quote log function args

diff --git a/src/bee b/src/bee
--- a/src/bee
+++ b/src/bee
@@ -16,26 +16,26 @@ IFS=$'\n\t'
 ################################################################################
 
 bee::log() {
-  echo "🐝 $*"
+  echo "🐝 "$*""
 }
 
 bee::log_warn() {
-  echo "⚠️ WARNING: $*" >&2
+  echo "⚠️ WARNING: "$*"" >&2
 }
 
 bee::log_error() {
-  echo "❌ ERROR: $*" >&2
+  echo "❌ ERROR: "$*"" >&2
 }
 
 bee::log_strong() {
   echo ""
   echo "################################################################################"
-  echo "# 🐝 $*"
+  echo "# 🐝 "$*""
   echo "################################################################################"
 }
 
 bee::log_func() {
-  bee::log_strong "${FUNCNAME[1]} $*"
+  bee::log_strong "${FUNCNAME[1]} "$*""
 }
 
 ################################################################################
