Revert "Remove migrations"
This reverts commit 40d38fc61968958954295923b3c09fa4d2d80e8f.

diff --git a/src/bee b/src/bee
--- a/src/bee
+++ b/src/bee
@@ -76,6 +76,27 @@ BEE_PLUGIN_REGISTRIES=(
 fi
 source "${HOME}/.beerc"
 
+# TODO: remove when expired (Dec 2020)
+bee_migration_0370() {
+  if [[ -f bee.sh ]]; then
+    log_warn "bee.sh is deprecated." "Please see CHANGELOG.md and apply the required actions!"
+    source bee.sh
+    BEE_PROJECT="${PROJECT}"
+    BEE_RESOURCES="${RESOURCES:-${BEE_RESOURCES}}"
+  fi
+}
+bee_migration_0370
+
+# TODO: remove when expired (Dec 2020)
+bee_migration_0380() {
+  command -v builtin_commands &> /dev/null || {
+    builtin_commands() {
+      internal_commands
+    }
+  }
+}
+bee_migration_0380
+
 if [[ -v BEE_RC ]]; then
   source "${BEE_RC}"
 else
